version: "3.8"

services:
  db:
    image: mariadb:10.11
    container_name: zabbix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: zabbix_root
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
    volumes:
      - db_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      MYSQL_ROOT_PASSWORD: zabbix_root
    ports:
      - "10050:10050"
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    depends_on:
      - db

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web
    restart: always
    environment:
      DB_SERVER_HOST: db
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_pass
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Africa/Casablanca
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - db
      - zabbix-server

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: zabbix-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: zabbix
      PMA_PASSWORD: zabbix_pass
    ports:
      - "8080:80"
    depends_on:
      - db

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    restart: always
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "zabbix-server"
    privileged: true
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /dev:/host/dev
    depends_on:
      - zabbix-server

volumes:
  db_data:
  zabbix_server_data: 
